### ISSUE TITLE
PATCH] This resolves issues with the gnu compiler error: no  declarations were found by argument-dependent lookup at the  point of instantiation.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vrjuggler/vrjuggler#55]
```
What steps will reproduce the problem?
1. Try to compile on openSUSE 12.3

What is the expected output? What do you see instead?
We get this in a couple of instances: was not declared in this scope, and no 
declarations were found by argument-dependent lookup at the point of 
instantiation [-fpermissive].


Please provide any additional information below.
http://blog.llvm.org/2009/12/dreaded-two-phase-name-lookup.html
http://stackoverflow.com/questions/10639053/name-lookups-in-c-templates


```

Original issue reported on code.google.com by `mc...@iastate.edu` on 14 Apr 2013 at 12:21

Attachments:
- [gadgeteer_this.patch](https://storage.googleapis.com/google-code-attachments/vrjuggler/issue-55/comment-0/gadgeteer_this.patch)
